//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProjetFilm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class drapeau
    {
        public int Id { get; set; }
        public string CheminImage { get; set; }
        public Nullable<int> Pays_Id { get; set; }
    
        public virtual pays pays { get; set; }
    }
}
