//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProjetFilm.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetFilmEntities1 : DbContext
    {
        public ProjetFilmEntities1()
            : base("name=ProjetFilmEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<drapeau> drapeau { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<pays> pays { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
